# Generated by Django 3.2.15 on 2022-08-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_remove_dialogos_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADBGeospatdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcode', models.CharField(max_length=10, verbose_name='Region Code')),
                ('rname', models.CharField(max_length=200, verbose_name='Region Name')),
                ('ccode', models.CharField(max_length=10, verbose_name='Country Code')),
                ('cname', models.CharField(max_length=200, verbose_name='Country Name')),
                ('scode', models.CharField(max_length=10, verbose_name='Subdivision Code')),
                ('sname', models.CharField(max_length=200, verbose_name='Subdivision Name')),
            ],
        ),
        migrations.CreateModel(
            name='ADBTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Position index')),
                ('code', models.CharField(max_length=3, verbose_name='Theme code')),
                ('name', models.CharField(max_length=200, verbose_name='Theme name')),
                ('desc', models.TextField(verbose_name='Theme description')),
                ('icon', models.FileField(upload_to='', verbose_name='Theme icon')),
            ],
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='adb_geospatdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.adbgeospatdivision'),
        ),
        migrations.AddField(
            model_name='resourcebase',
            name='adb_themes',
            field=models.ManyToManyField(blank=True, null=True, to='base.ADBTheme'),
        ),
    ]
